# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-16 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Users',
            name='mobile_no',
            field=models.IntegerField(),
        ),
    ]
