# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-16 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0005_registereduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisteredUser',
        ),
    ]
